controller_manager:
  ros__parameters:
    update_rate: 10 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController 
      
    gripper_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController    

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_wheel_joint", "rear_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint", "rear_right_wheel_joint"]

    wheel_separation: 0.512 #0.1  # 0.256  # 0.512
    wheels_per_side: 1 # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.1651 # 0.015

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Preserve turning radius when limiting speed/acceleration/jerk
    preserve_turning_radius: true

    # Publish limited velocity
    publish_cmd: true

    # Publish wheel data
    publish_wheel_data: true

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0 

joint_trajectory_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
      
    command_interfaces:
      - position
      
    state_interfaces:
      - position
      - velocity
      
    gains:
      panda_joint1:
        p: 4000.0
        d: 10.0
        i: 250.0
        i_clamp: 15.0
        ff_velocity_scale: 0.0
      panda_joint2:
        p: 10000.0
        d: 25.0
        i: 600.0
        i_clamp: 45.0
        ff_velocity_scale: 0.0
      panda_joint3:
        p: 8000.0
        d: 20.0
        i: 450.0
        i_clamp: 30.0
        ff_velocity_scale: 0.0
      panda_joint4:
        p: 6000.0
        d: 15.0
        i: 300.0
        i_clamp: 30.0
        ff_velocity_scale: 0.0
      panda_joint5:
        p: 3000.0
        d: 5.0
        i: 175.0
        i_clamp: 7.0
        ff_velocity_scale: 0.0
      panda_joint6:
        p: 2500.0
        d: 3.0
        i: 150.0
        i_clamp: 6.0
        ff_velocity_scale: 0.0
      panda_joint7:
        p: 2000.0
        d: 2.0
        i: 10.0
        i_clamp: 5.0
        ff_velocity_scale: 0.0
        
gripper_trajectory_controller:
  ros__parameters:
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      panda_finger_joint1:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0
      panda_finger_joint2:
        p: 225.0
        d: 0.001
        i: 0.4
        i_clamp: 4.0


